POST http://127.0.0.1:5000/feedbacks
Content-Type: application/json

{
    "id": "4444c5dv-4569-5236-7410-521adf5c1ca6",
    "feedback": "Estou gostando muito da plataforma! Só seria legal se fosse possível editar as preferências de notificações."
}
