POST http://127.0.0.1:5000/feedbacks
Content-Type: application/json

{
    "id": "7001a18c-60d7-7703-8475-161vz16f6177",
    "feedback": "Gosto muito de usar o Alumind! Está me ajudando bastante em relação a alguns problemas que tenho. Só queria que houvesse uma forma mais fácil de eu mesmo realizar a edição do meu perfil dentro da minha conta"
}
